os: windows
language: sh
python:
- '3.7'
before_install:
- git config --local user.name "Twopape"
- git config --local user.email "cwoolfries2@my.bcit.ca"
- choco install python3
- export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
- python -m pip install --upgrade pip wheel
- python -m pip install --extra-index-url https://pypi.org/project/pywin32/ pywin32
- python -m pip install --extra-index-url https://pypi.org/simple/ pygame
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
virtualenv:
  system_site_packages: true
  deploy:
  provider: releases
  on:
    repo: Twopape/SnakeGame
  skip_cleanup: 'true'
